###

GET http://localhost:9999/banners.getById?id=1&title=Депозиты с доходом 60/40 HTTP/1.1 HTTP/1.1

###

GET http://localhost:9999/banners.getAll HTTP/1.1

###

GET http://localhost:9999/posts.save/?id=0&title=Депозиты с доходом 60/40&... HTTP/1.1
